### ISSUE TITLE
[BUG] Vulkan only showing up as a preset flag despite it being removed from the rendering mode preset

### ISSUE THREAD

**Issue by Mugetsu895** [bloxstraplabs/bloxstrap#2697]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] My answer given in the checkbox above is a lie.

### What problem did you encounter?

Well the title already explains it but basically vulkan doesnt show up in the fastflag editor unless you click preset flags despite vulkan being removed from the rendering mode preset

https://github.com/user-attachments/assets/f1e1c5f3-20f8-4a34-b40c-59884c39c1a7
 video above illustrates what i mean

**Comment by Storm-930** [comment]
actual bug this time what
so Vulkan got removed from the preset options because too many people who thought it was free FPS ended up crashing because their GPUs are shittier than mine
it _is_ or at least was made a code comment left in the part with the preset flags, but the flag itself is still marked as a preset even if the option doesn't show it

**Comment by Storm-930** [comment]
just a slight oversight

**Comment by pizzaboxer** [comment]
Good catch.
