### ISSUE TITLE
[REQ] A dedicated website page for sharing mods

### ISSUE THREAD

**Issue by red-nt** [bloxstraplabs/bloxstrap#3346]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Since bloxstrap has a website, I thought what if you guys made a website page dedicated to sharing mods. It would be much easier to search and find the mod you like. Sometimes on discord some of the popular mods are a bit deep and sometimes searching for a specific mod in discord could be quite inconvenient. So by adding a website page dedicated to sharing mods. Sharing mods would be easier than ever.

**Comment by Skylan031** [comment]
i think this would require a whole account system and i honestly dont think this would be that worth it

**Comment by Wanwood1** [comment]
This seems a bit hard to do, as this would require a database, time spent into coding and more resource usage.
Maybe in the future if the bloxstrap developers had more donations coming through, they might think of this unique idea.

**Comment by BizzarBlitz** [comment]
I agree in concept but in reality this seems like a terrible idea because you would need to account for literally all of the following issues:
- Account system (could probably use Github/Discord auth for this but still)
- Media hosting costs
- Moderation
  - Anti-spam protection
- (Certain) mods becoming outdated pretty much every Roblox update

I think a section on the website showcasing good mods (e.g. ones with the Seal of Approval tag) and providing links to the Discord forum posts for each would be cool, but providing an actual marketplace not so much.

**Comment by pizzaboxer** [comment]
This is something that has been at the forefront of my mind for quite literally the past year. It's not a priority for me, though. I'll close this because I am well aware of the idea, and because I don't expect to be working on it very soon.
