### ISSUE TITLE
[REQ] Bloxshade Integration

### ISSUE THREAD

**Issue by mavenboard** [bloxstraplabs/bloxstrap#3546]
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Before I start, this is not "RoShade" this is "BloxShade". I would love for BloxShade to be integrated so that I wouldnt have to install both, making the process longer. BloxShade is by Extravi, and is under the GPL3.0 license which states free use and distribution. Please consider this request, and thanks!

**Comment by bluepilledgreat** [comment]
no

**Comment by pizzaboxer** [comment]
I'll elaborate: I don't want to have it built in as part of Bloxstrap because the functionality for it is complex enough for it to be its own application. We don't want to be handling it along with what we already need to be handling, and it works well if Extravi manages it independently while we manage our own stuff.
