### ISSUE TITLE
[BUG] bro what is this help 😭😭😭

### ISSUE THREAD

**Issue by tiks22667** [bloxstraplabs/bloxstrap#3768]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

?

### What problem did you encounter?

![imagen_2024-11-15_164221442](https://github.com/user-attachments/assets/d543a6ec-3525-44e1-afbb-bd862b9087ae)

****

### Bloxstrap Log

```text
idk
```

**Comment by RyanLua** [comment]
Please [edit your issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/editing-an-issue) to answer the missing fields properly (Bloxstrap Version & Bloxstrap Log). We cannot help you if you just submit a screenshot with no explanation and your title makes it so that it is less helpful for those in the future with the same issue as you.

* Include an explanation of the issue that is happening and how you got there
* Add in your Bloxstrap version and logs
* Steps to reproduce the bug you are having so others can recreate it and find a solution

**Comment by nabheyka880** [comment]
what version are you using

**Comment by Wanwood1** [comment]
update you sad loser

**Comment by tiks22667** [comment]
how???????

________________________________
De: Wanwood ***@***.***>
Enviado: sábado, 16 de noviembre de 2024 8:52
Para: bloxstraplabs/bloxstrap ***@***.***>
Cc: tiks22667 ***@***.***>; Author ***@***.***>
Asunto: Re: [bloxstraplabs/bloxstrap] [BUG] bro what is this help 😭😭😭 (Issue #3768)


update you sad loser

**Comment by nabheyka880** [comment]
https://bloxstraplabs.com/
how can you say how to update when you've literally downloaded bloxstrap
like just do it again but with the latest version

**Comment by balleranimates** [comment]
edit

**Comment by nmac101** [comment]
bro really checked the last checkbox 💀

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.
