### ISSUE TITLE
Bloxstrap for mobile

### ISSUE THREAD

**Issue by Deadlydarty** [bloxstraplabs/bloxstrap#3817]
### Acknowledgement of preliminary instructions

- [ ] I have read and acknowledged the preliminary instructions.

### What idea do you have?

I was wondering if it was possible to make bloxstrap on mobile because I can't deal with the slow and laggy Roblox mobile app that the only thing it does is to take up my storage please help

**Comment by theletron** [comment]
1. Bloxstrap is a **bootstrapper**, not a Roblox app alternative.
2. Bloxstrap is only for **PCs running Windows**.
3. Bloxstrap does not reduce storage that Roblox uses.
4. The mobile version of Roblox does not have a bootstrapper.
5. Roblox is laggy because you are either **low on storage, low on RAM, or don't have a good phone**.

**Comment by Enrico000067** [comment]
Hi

**Comment by suow1113** [comment]
Hi

**Comment by Marko11111111333333333** [comment]
Then what will happen if i try to download it on mobile?

**Comment by Deku737636** [comment]
Quiero descargar bloxstrap para tener más fps y reducir el lag

**Comment by KammyUnix** [comment]
@Marko11111111333333333 you wont be able to run it

**Comment by sharkcute17-coder** [comment]
wh

**Comment by sharkcute17-coder** [comment]
A
